@echo off
::
:: Copyright (C) 2024 Robert Di Pardo
::
:: Permission to use, copy, modify, and/or distribute this software for any purpose
:: with or without fee is hereby granted.
::
:: THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
:: REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
:: AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
:: INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
:: LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
:: OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
:: PERFORMANCE OF THIS SOFTWARE.
::
SETLOCAL

set "VERSION=1.3.3.0"
set "PLUGIN=PreviewHTML"
set "CONFIG_DIR=.\src\Config"
set "PLUGIN_DLL=.\out\Win32\Release\%PLUGIN%.dll"
set "PLUGINX64_DLL=.\out\Win64\Release\%PLUGIN%.dll"
set "SLUG_NAME=.\out\%PLUGIN%_v%VERSION%_win32"
set "SLUGX64_NAME=.\out\%PLUGIN%_v%VERSION%_x64"
set "SLUG=%SLUG_NAME%.zip"
set "SLUGX64=%SLUGX64_NAME%.zip"

del /S /Q /F .\out\*.zip 2>NUL:
call %~dp0build.cmd

7z a -tzip "%SLUG%" "%PLUGIN_DLL%" *.txt %CONFIG_DIR%\*.ini -y
7z a -tzip "%SLUGX64%" "%PLUGINX64_DLL%" *.txt %CONFIG_DIR%\*.ini -y

ENDLOCAL
